CREATE TABLE "public"."ADMIN" (
  "admin_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "login"    text   NOT NULL,
  "passhash" text   NOT NULL,
  CONSTRAINT "ADMIN_pkey" PRIMARY KEY (admin_id)
);
CREATE TABLE "public"."BOOKING" (
  "booking_id"   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "master_id"    bigint NOT NULL,
  "user_id"      bigint NOT NULL,
  "service_id"   bigint NOT NULL,
  "booking_date" text   NOT NULL,
  CONSTRAINT "BOOKING_pkey" PRIMARY KEY (booking_id)
);
CREATE TABLE "public"."CATEGORY" (
  "category_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name"        text   NOT NULL,
  "description" text,
  "preview"     text,
  CONSTRAINT "CATEGORY_pkey" PRIMARY KEY (category_id)
);
CREATE TABLE "public"."MASTER" (
  "master_id"  bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "login"      text   NOT NULL,
  "passhash"   text   NOT NULL,
  "name"       text   NOT NULL,
  "picture"    text,
  "scheme_id"  bigint NOT NULL,
  "experience" text,
  CONSTRAINT "MASTER_login_key" UNIQUE (LOGIN),
  CONSTRAINT "MASTER_pkey" PRIMARY KEY (master_id)
);
CREATE TABLE "public"."SERVICE" (
  "service_id"  bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name"        text   NOT NULL,
  "description" text   NOT NULL,
  "preview"     text   NOT NULL,
  "category_id" bigint,
  CONSTRAINT "SERVICE_pkey" PRIMARY KEY (service_id)
);
CREATE TABLE "public"."USER" (
  "user_id"  bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "login"    text,
  "passhash" text,
  "name"     text,
  "picture"  text,
  CONSTRAINT "USER_pkey" PRIMARY KEY (user_id)
);
CREATE TABLE "public"."WORK_SCHEME" (
  "scheme_id" bigint  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "sunday"    boolean NOT NULL,
  "monday"    boolean NOT NULL,
  "tuesday"   boolean NOT NULL,
  "wednesday" boolean NOT NULL,
  "thursday"  boolean NOT NULL,
  "friday"    boolean NOT NULL,
  "saturday"  boolean NOT NULL,
  CONSTRAINT "WORK_SCHEME_pkey" PRIMARY KEY (scheme_id)
);
ALTER TABLE "public"."BOOKING"
  ADD CONSTRAINT "BOOKING_master_id_fkey" FOREIGN KEY (master_id) REFERENCES public."MASTER"(master_id);
ALTER TABLE "public"."SERVICE"
  ADD CONSTRAINT "SERVICE_category_id_fkey" FOREIGN KEY (category_id) REFERENCES public."CATEGORY"(category_id);
ALTER TABLE "public"."BOOKING"
  ADD CONSTRAINT "BOOKING_service_id_fkey" FOREIGN KEY (service_id) REFERENCES public."SERVICE"(service_id);
ALTER TABLE "public"."BOOKING"
  ADD CONSTRAINT "BOOKING_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."USER"(user_id);
ALTER TABLE "public"."MASTER"
  ADD CONSTRAINT "MASTER_scheme_id_fkey" FOREIGN KEY (scheme_id) REFERENCES public."WORK_SCHEME"(scheme_id);
CREATE POLICY "All in policy 28jn_0" ON "storage"."objects"
  FOR SELECT
  TO PUBLIC
  USING (((bucket_id = 'img'::text) AND true));
CREATE POLICY "All in policy 28jn_1" ON "storage"."objects"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (((bucket_id = 'img'::text) AND true));
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."ADMIN" TO "anon", "authenticated", "postgres", "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."BOOKING" TO "anon", "authenticated", "postgres", "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."CATEGORY" TO "anon", "authenticated", "postgres", "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."MASTER" TO "anon", "authenticated", "postgres", "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."SERVICE" TO "anon", "authenticated", "postgres", "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."USER" TO "anon", "authenticated", "postgres", "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."WORK_SCHEME" TO "anon", "authenticated", "postgres", "service_role";
